### ISSUE TITLE
Navigating to the site having been on another tab for a while makes Morpeko dizzy

### ISSUE THREAD

**Issue by james-work-account** [simeydotme/pokemon-cards-css#12]
Video demonstration:

https://user-images.githubusercontent.com/31282758/199218551-dd972f86-3091-4efa-b1ee-94ab0562d375.mp4

Having had the tab open in the background for a while, opening the tab up again makes the top card (Morpeko) spin uncontrolably for a while. My assumption is that it is catching up with all of the mouse motion that has happened since the tab was last open but I could be wrong.

I've seen this in Firefox (106.0.3), Safari (16.1), and Chrome (107.0.5304.87).

**Comment by james-work-account** [comment]
Actually, having recorded this Issue I tabbed back to the page and Bulbasaur was spinning uncontrolably this time - maybe it's just the last card that was moused-over since switching away from the page?

**Comment by simeydotme** [comment]
THanks @james-work-account , I thought I had resolved it with; https://github.com/simeydotme/pokemon-cards-css/commit/64947d8d08d7393019dc303ddde0c1eb653049fe#diff-a138b838fb404245a365da66d24bd0df6376c8bcd072ad3f3e768e5ed3834fa2R50-R52 but I noticed it again today.

I think I'll have to add a `onvisibilitychange` listener, too, as I guess it's triggering an `interact` when returning from an inactive tab and bypassing this check.

**Comment by simeydotme** [comment]
@james-work-account if you get a chance, could you see if you are able to reproduce this anymore?

Thanks! :)

**Comment by james-work-account** [comment]
LGTM @simeydotme 👍🏼

**Comment by simeydotme** [comment]
I did see there's still the freak-out happening on the shine / glare layers, but it only lasts for a second, so I'll ignore it for now
