### ISSUE TITLE
Request a Getting Started guide

### ISSUE THREAD

**Issue by zbloss** [simeydotme/pokemon-cards-css#18]
Maybe this is a dumb question, but I'm pretty new to css in general.

I loaded the global.css and pokemon.css stylesheets into my react app, and I believe I followed the class names correctly but I'm not seeing the styles being applied to my images.

I would be happy to contribute to a getting started guide if I could get this working correctly.

**Comment by anopheles** [comment]
Is there a recommended approach to get this into your own (react) project? Perhaps a publishable npm package that one can easily integrate into their project as per https://github.com/simeydotme/pokemon-cards-css/issues/15

**Comment by phiilu** [comment]
I have managed to port the effects to my app which is a plain LiveView app with a bit of Alpine.js. I am using Popmotion to achieve the spring effects. I think the general approach is to copy the assets and .css files (the Svelte scoped css too) and than try to implement the event handlers from `card.svelte` with your framework of choice. With React I would probably take a look at Framer Motion and using the `useSpring` hook. The only things I could not copy exactly was the spring values as the seem to be different in Popmotion than in svelte/motion. 

If I have time I could take a look and check if I can re-create this project in Alpine.js and maybe React.

**Comment by simeydotme** [comment]
> Is there a recommended approach to get this into your own (react) project? Perhaps a publishable npm package that one can easily integrate into their project as per #15

please see #19 

Essentially, without trying to sound too rude; if you're unable to extract the parts you need and implement them in your own application architecture (and hopefully modify to suit your needs), then you should avoid even attempting to use them. These powerful effects demand responsible usage 🙂 

------

I am, however, working on a "breakdown" of the effect to explain how different versions of it work visually. But I need time. This was a tech demo / prototype and definitely not expected to be in such demand 😂 thankyou for your patience _(star and watch for updates)_
