### ISSUE TITLE
Card hierarchy problem

### ISSUE THREAD

**Issue by zzy-life** [simeydotme/pokemon-cards-css#25]
![image](https://user-images.githubusercontent.com/68179477/203681916-978fa203-673f-4626-a2d0-e26c5622d66c.png)

![image](https://user-images.githubusercontent.com/68179477/203682214-c42283ef-84f0-4535-893a-d61419a5bfb3.png)

As shown in the figure, the Card are always blocked by the ones with higher order. Can you tell me why?

**Comment by simeydotme** [comment]
no, sorry

**Comment by zzy-life** [comment]
Sorry, because I added a div to the outside of the card tag
