### ISSUE TITLE
Thanks to the author, I made the npm package

### ISSUE THREAD

**Issue by zzy-life** [simeydotme/pokemon-cards-css#29]
Currently, the test is available in vue2. Please use 
```
npm i vue-pokemon-cards-css

```
library  (https://github.com/zzy-life/components-pokemon-cards-css)
Thanks again (https://github.com/Maurier/vue-pokemon-cards-css) Vue implementation

**Comment by simeydotme** [comment]
uhhhh, not sure how I feel about flat-out copying my work and posting on another platform.
Appreciate the link backs (for now)

**Comment by zzy-life** [comment]
Just to get more people to use this
support also uses your.

**Comment by IlhamriSKY** [comment]
Hello i try make my own style thanks for your hard work,

https://github.com/IlhamriSKY/Card-glare-project
