### ISSUE TITLE
Why do I lose the light and shadow effect of the official website when I deploy it locally?

### ISSUE THREAD

**Issue by sanbei011** [simeydotme/pokemon-cards-css#42]
![image](https://github.com/simeydotme/pokemon-cards-css/assets/95988545/78030404-1cea-4a60-9d51-8b54dcb0824d)
**When I run it locally, I can't seem to achieve a similar lighting effect as the official website, why is that?**

**Comment by Nate603** [comment]
same thing happened to me, seems to be a ton of errors in the network tab/console

**Comment by simeydotme** [comment]
it's not really supposed to be "runnable" , it's just the code I used for posterity.

However, the problems you're likely having is the "foil" and "etch" files which are used as masks for the card effects are hosted on my CDN. Which is not publicly accessible, so you'd need to download the etches and mask from somewhere like https://malie.io/ 

alternatively, you can manually call the Card.svelte file; https://github.com/simeydotme/pokemon-cards-css/blob/main/src/lib/components/Card.svelte#L8-L22 with these props set to whatever you want. The "CardProxy" file tries to get the correct mask/foil images from my CDN, so you can skip that.
