### ISSUE TITLE
Can the card size change with the image?

### ISSUE THREAD

**Issue by Amezora** [simeydotme/pokemon-cards-css#48]
If the image resolution is too large, the display result will be an extruded image, but I can't find the attribute that affects this effect. Please tell me!

**Comment by Amezora** [comment]
Hello!
Sorry, I didn't express myself well enough.
(My skills are very poor, please forgive me if I offend you!)
As shown in the picture, when the picture size and the card size are different, the picture will adapt to the card, so is there a way to make the card size change with the picture size, and create cards of different sizes based on each picture of different sizes?
![Snipaste_2024-09-06_01-11-04](https://github.com/user-attachments/assets/ae2e6cb3-2de2-4484-abef-29146c179ad0)

**Comment by simeydotme** [comment]
oh, i understand now...

yes, there's a `aspect-ratio` value which can be changed to `auto` ... that is currently set to the specific size of a pokemon card. But if set to 'auto' it will take the size of the image inside :) 

<img width="243" alt="Screenshot 2024-09-06 at 10 54 05" src="https://github.com/user-attachments/assets/a9453371-5a7f-40f9-8888-75988d0090ab">
<img width="780" alt="Screenshot 2024-09-06 at 10 54 32" src="https://github.com/user-attachments/assets/cb4840bb-79af-4c2a-a694-6c87351ab906">

**Comment by Amezora** [comment]
Thank you so much for your help :)

in the `base.css` (public/css/cards/base.css), modify the two `aspect-ratio: var(--card-aspect);` to `aspect-ratio: auto;`
